# Generated by Django 2.2.5 on 2019-09-21 10:15

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgpath', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount_given', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Distributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributorcode', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('bill2contact_number', models.CharField(max_length=20)),
                ('bill2address', models.TextField()),
                ('paymentterms', models.CharField(max_length=200)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Discounts')),
            ],
            options={
                'verbose_name_plural': 'Distributor',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=200)),
                ('unitnetweight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('grossweight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('unitprice', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('retailprice', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('productdescription', models.TextField(max_length=200)),
                ('dimensions', models.CharField(max_length=200)),
                ('carton_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('carton_dimensions', models.CharField(max_length=200)),
                ('carton_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.CharField(max_length=200)),
                ('imgpath', models.TextField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ship2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sub Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Products')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subcategory'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('invoiceno', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('qty1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty7', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty8', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty9', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty10', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty11', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty12', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty13', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty14', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty15', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty16', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty17', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty18', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty19', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty20', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty21', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty22', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty23', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty24', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty25', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty26', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty27', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty28', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty29', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('qty30', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('address', models.CharField(max_length=200)),
                ('prefferedtiming', models.CharField(max_length=200)),
                ('preffereddate', models.CharField(max_length=200)),
                ('pickuptime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deliveredtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cashtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cashconfirmtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Distributors')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item1', to='main.Products')),
                ('line10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item10', to='main.Products')),
                ('line11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item11', to='main.Products')),
                ('line12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item12', to='main.Products')),
                ('line13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item13', to='main.Products')),
                ('line14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item14', to='main.Products')),
                ('line15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item15', to='main.Products')),
                ('line16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item16', to='main.Products')),
                ('line17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item17', to='main.Products')),
                ('line18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item18', to='main.Products')),
                ('line19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item19', to='main.Products')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item2', to='main.Products')),
                ('line20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item20', to='main.Products')),
                ('line21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item21', to='main.Products')),
                ('line22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item22', to='main.Products')),
                ('line23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item23', to='main.Products')),
                ('line24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item24', to='main.Products')),
                ('line25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item25', to='main.Products')),
                ('line26', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item26', to='main.Products')),
                ('line27', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item27', to='main.Products')),
                ('line28', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item28', to='main.Products')),
                ('line29', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item29', to='main.Products')),
                ('line3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item3', to='main.Products')),
                ('line30', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item30', to='main.Products')),
                ('line4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item4', to='main.Products')),
                ('line5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item5', to='main.Products')),
                ('line6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item6', to='main.Products')),
                ('line7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item7', to='main.Products')),
                ('line8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item8', to='main.Products')),
                ('line9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item9', to='main.Products')),
            ],
        ),
        migrations.AddField(
            model_name='distributors',
            name='ship2address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ship2'),
        ),
        migrations.AddField(
            model_name='distributors',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=200)),
                ('imgpath', models.TextField(max_length=200)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tag')),
            ],
        ),
    ]
