# Generated by Django 2.2.4 on 2019-10-04 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='ship2',
            options={'verbose_name_plural': 'ship2'},
        ),
        migrations.AlterField(
            model_name='products',
            name='retailprice',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='unitprice',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
