# Generated by Django 2.2.4 on 2019-10-17 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191009_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='discount_given',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
